name: dezire-notebook-frontend

on:
  push:

jobs:
  Node_js_build:
    runs-on: ubuntu-latest
    steps:
      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE

      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install dependencies
        run: |
          yarn install
          yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: dezire-notebook-frontend-build
          path: ./build

  Docker_image_build:
    runs-on: ubuntu-latest
    needs: Node_js_build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dezire-notebook-frontend-build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dezire
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        # env:
        # DOCKER_BUILDKIT: 1
        # with:
        #   push: true
        #   tags: docker.io/dezire/notebook-frontend:latest
        run: |
          docker buildx build -t dezire/notebook-frontend:latest .
          docker tag dezire/notebook-frontend:latest dezire/notebook-frontend:latest
          docker push dezire/notebook-frontend:latest
