name: dezire-notebook-frontend

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install dependencies
        run: |
          yarn install
          yarn build

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: [buildx]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - run: mkdir ./build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dezire
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: docker.io/dezire/notebook-frontend:latest
